version: "2"

run:
  go: "1.25"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
