package server

import (
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/jedarden/armor/internal/validate"
)

// TestAcceptance_EnhancedStatusCodeErrors verifies the acceptance criteria for enhanced status code errors.
//
// Acceptance Criteria:
// 1. Use the new error formatting helper for status code errors
// 2. Include expected status code(s) in error message
// 3. Include actual received status code in error message
// 4. Include context about which HTTP method/endpoint was being validated
// 5. Add tests verifying the enhanced error message content
func TestAcceptance_EnhancedStatusCodeErrors(t *testing.T) {
	t.Run("Criterion1_UsesErrorFormattingHelper", func(t *testing.T) {
		// Test that enhanced functions use the validation error formatting helper
		err := ValidateStatusCodeInt(200, 404)
		if err == nil {
			t.Fatal("Expected error for non-matching codes")
		}

		// Verify it's a ValidationError type
		validationErr, ok := err.(validate.ValidationError)
		if !ok {
			t.Fatalf("Expected validate.ValidationError type, got %T", err)
		}

		// Verify error type is set
		if validationErr.ErrorType != "status_code" {
			t.Errorf("Expected ErrorType 'status_code', got '%s'", validationErr.ErrorType)
		}

		// Verify suggestions are present (auto-generated by the helper)
		if len(validationErr.Suggestions) == 0 {
			t.Error("Expected auto-generated suggestions from error formatting helper")
		}
	})

	t.Run("Criterion2_IncludesExpectedStatusCode", func(t *testing.T) {
		tests := []struct {
			name     string
			expected int
			actual   int
		}{
			{"Single expected code 200", 200, 404},
			{"Single expected code 404", 404, 200},
			{"Single expected code 500", 500, 403},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				err := ValidateStatusCodeInt(tt.expected, tt.actual)
				if err == nil {
					t.Fatal("Expected error for non-matching codes")
				}

				errorMsg := err.Error()
				expectedStr := string(rune('0' + tt.expected/100)) + string(rune('0' + (tt.expected%100)/10)) + string(rune('0' + tt.expected%10))

				if !strings.Contains(errorMsg, expectedStr) {
					t.Errorf("Error message should contain expected code '%d', got: %s", tt.expected, errorMsg)
				}

				// Verify it's stored in the ValidationError
				validationErr := err.(validate.ValidationError)
				expectedVal, ok := validationErr.Expected.(int)
				if !ok || expectedVal != tt.expected {
					t.Errorf("Expected value should be %d (int), got %v (%T)", tt.expected, validationErr.Expected, validationErr.Expected)
				}
			})
		}

		t.Run("Multiple expected codes", func(t *testing.T) {
			allowedCodes := []int{200, 201, 204}
			err := ValidateStatusCodeIntAny(allowedCodes, 404)
			if err == nil {
				t.Fatal("Expected error for non-matching codes")
			}

			errorMsg := err.Error()

			// Verify all allowed codes are mentioned
			for _, code := range allowedCodes {
				codeStr := string(rune('0' + code/100)) + string(rune('0' + (code%100)/10)) + string(rune('0' + code%10))
				if !strings.Contains(errorMsg, codeStr) {
					t.Errorf("Error message should mention allowed code %d, got: %s", code, errorMsg)
				}
			}

			// Verify "one of" phrasing
			if !strings.Contains(strings.ToLower(errorMsg), "one of") {
				t.Errorf("Error should use 'one of' phrasing for multiple codes, got: %s", errorMsg)
			}
		})
	})

	t.Run("Criterion3_IncludesActualStatusCode", func(t *testing.T) {
		tests := []struct {
			name     string
			expected int
			actual   int
		}{
			{"Actual code 404", 200, 404},
			{"Actual code 200", 404, 200},
			{"Actual code 500", 403, 500},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				err := ValidateStatusCodeInt(tt.expected, tt.actual)
				if err == nil {
					t.Fatal("Expected error for non-matching codes")
				}

				errorMsg := err.Error()
				actualStr := string(rune('0' + tt.actual/100)) + string(rune('0' + (tt.actual%100)/10)) + string(rune('0' + tt.actual%10))

				if !strings.Contains(errorMsg, actualStr) {
					t.Errorf("Error message should contain actual code '%d', got: %s", tt.actual, errorMsg)
				}

				// Verify it's stored in the ValidationError
				validationErr := err.(validate.ValidationError)
				actualVal, ok := validationErr.Actual.(int)
				if !ok || actualVal != tt.actual {
					t.Errorf("Actual value should be %d (int), got %v (%T)", tt.actual, validationErr.Actual, validationErr.Actual)
				}
			})
		}
	})

	t.Run("Criterion4_IncludesHTTPContext", func(t *testing.T) {
		tests := []struct {
			name        string
			httpContext HTTPContext
			expected    int
			actual      int
			contextInMsg string
		}{
			{
				"GET /api/users/123",
				HTTPContext{Method: "GET", Endpoint: "/api/users/123"},
				200, 404,
				"GET /api/users/123",
			},
			{
				"POST /api/orders",
				HTTPContext{Method: "POST", Endpoint: "/api/orders"},
				201, 409,
				"POST /api/orders",
			},
			{
				"DELETE /api/users/123",
				HTTPContext{Method: "DELETE", Endpoint: "/api/users/123"},
				204, 403,
				"DELETE /api/users/123",
			},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				err := ValidateStatusCodeIntWithContext(tt.expected, tt.actual, tt.httpContext)
				if err == nil {
					t.Fatal("Expected error for non-matching codes")
				}

				errorMsg := err.Error()

				// Verify HTTP context is in error message
				if !strings.Contains(errorMsg, tt.contextInMsg) {
					t.Errorf("Error message should contain HTTP context '%s', got: %s", tt.contextInMsg, errorMsg)
				}

				// Verify HTTP method is mentioned
				if !strings.Contains(errorMsg, tt.httpContext.Method) {
					t.Errorf("Error message should contain HTTP method '%s', got: %s", tt.httpContext.Method, errorMsg)
				}

				// Verify endpoint is mentioned
				if !strings.Contains(errorMsg, tt.httpContext.Endpoint) {
					t.Errorf("Error message should contain endpoint '%s', got: %s", tt.httpContext.Endpoint, errorMsg)
				}

				// Verify context is stored in ValidationError
				validationErr := err.(validate.ValidationError)
				if !strings.Contains(validationErr.Context, tt.contextInMsg) {
					t.Errorf("ValidationError.Context should contain '%s', got: %s", tt.contextInMsg, validationErr.Context)
				}
			})
		}

		t.Run("HTTP context with multiple allowed codes", func(t *testing.T) {
			httpContext := HTTPContext{Method: "GET", Endpoint: "/api/users/123"}
			allowedCodes := []int{200, 404}
			err := ValidateStatusCodeIntAnyWithContext(allowedCodes, 500, httpContext)
			if err == nil {
				t.Fatal("Expected error for non-matching codes")
			}

			errorMsg := err.Error()

			// Verify HTTP context is present
			if !strings.Contains(errorMsg, "GET /api/users/123") {
				t.Errorf("Error message should contain HTTP context, got: %s", errorMsg)
			}
		})
	})

	t.Run("Criterion5_VerifiesTestCoverage", func(t *testing.T) {
		// This test verifies that comprehensive tests exist for the enhanced functionality
		// We check this by testing the key scenarios

		t.Run("Enhanced functions exist and work", func(t *testing.T) {
			// Test ValidateStatusCodeInt
			err := ValidateStatusCodeInt(200, 404)
			if err == nil {
				t.Error("ValidateStatusCodeInt should return error for mismatch")
			} else {
				validationErr := err.(validate.ValidationError)
				if validationErr.ErrorType == "" {
					t.Error("ValidateStatusCodeInt should use ValidationError type")
				}
			}

			// Test ValidateStatusCodeIntWithContext
			ctx := HTTPContext{Method: "GET", Endpoint: "/api/test"}
			err = ValidateStatusCodeIntWithContext(200, 404, ctx)
			if err == nil {
				t.Error("ValidateStatusCodeIntWithContext should return error for mismatch")
			} else {
				validationErr := err.(validate.ValidationError)
				if validationErr.Context == "" {
					t.Error("ValidateStatusCodeIntWithContext should include context")
				}
			}

			// Test ValidateStatusCodeIntAny
			err = ValidateStatusCodeIntAny([]int{200, 201}, 404)
			if err == nil {
				t.Error("ValidateStatusCodeIntAny should return error for mismatch")
			} else {
				validationErr := err.(validate.ValidationError)
				if len(validationErr.Suggestions) == 0 {
					t.Error("ValidateStatusCodeIntAny should provide suggestions")
				}
			}

			// Test ValidateStatusCodeIntAnyWithContext
			err = ValidateStatusCodeIntAnyWithContext([]int{200, 201}, 404, ctx)
			if err == nil {
				t.Error("ValidateStatusCodeIntAnyWithContext should return error for mismatch")
			} else {
				validationErr := err.(validate.ValidationError)
				if validationErr.Context == "" {
					t.Error("ValidateStatusCodeIntAnyWithContext should include context")
				}
			}
		})

		t.Run("Error messages are comprehensive", func(t *testing.T) {
			err := ValidateStatusCodeIntWithContext(200, 404, HTTPContext{Method: "GET", Endpoint: "/api/users/123"})
			if err == nil {
				t.Fatal("Expected error for non-matching codes")
			}

			errorMsg := err.Error()
			validationErr := err.(validate.ValidationError)

			// Check for comprehensive error components
			requiredComponents := []string{
				"status_code",
				"200",
				"404",
				"GET /api/users/123",
			}

			for _, component := range requiredComponents {
				if !strings.Contains(errorMsg, component) {
					t.Errorf("Comprehensive error should contain '%s', got: %s", component, errorMsg)
				}
			}

			// Verify structured error fields are populated
			if validationErr.ErrorType == "" {
				t.Error("ValidationError should have ErrorType set")
			}
			if validationErr.Expected == nil {
				t.Error("ValidationError should have Expected set")
			}
			if validationErr.Actual == nil {
				t.Error("ValidationError should have Actual set")
			}
			if validationErr.Context == "" {
				t.Error("ValidationError should have Context set")
			}
			if len(validationErr.Suggestions) == 0 {
				t.Error("ValidationError should have Suggestions")
			}
		})
	})
}

// TestAcceptance_BackwardCompatibility verifies that existing functionality still works.
func TestAcceptance_BackwardCompatibility(t *testing.T) {
	t.Run("Existing functions still work", func(t *testing.T) {
		// Test that existing test helpers still work
		w := httptest.NewRecorder()
		w.WriteHeader(200)

		// These should not panic
		ValidateStatusCode(t, w, 200)
		CheckStatusCode(w, 200)
		ValidateStatusCodeAny(t, w, []int{200, 201, 204})
		CheckStatusCodeAny(w, []int{200, 201, 204})
		ValidateStatusCodeRange(t, w, 200, 299)
		CheckStatusCodeRange(w, 200, 299)
	})

	t.Run("Error messages are improved but compatible", func(t *testing.T) {
		w := httptest.NewRecorder()
		w.WriteHeader(404)

		// Use AssertStatusCode to get error details
		result := AssertStatusCode(w, 200, true)

		if result.Match {
			t.Error("Expected validation to fail")
		}

		// Error should still contain expected and actual codes
		if !strings.Contains(result.Error, "200") {
			t.Error("Error should contain expected code 200")
		}
		if !strings.Contains(result.Error, "404") {
			t.Error("Error should contain actual code 404")
		}

		// Should now include ValidationError
		if result.ValidationError.ErrorType == "" {
			t.Error("Result should include ValidationError")
		}
	})
}
