package validate

import (
	"strings"
	"testing"
)

// TestFormatValidationError_CustomSuggestions tests that custom suggestions work correctly
func TestFormatValidationError_CustomSuggestions(t *testing.T) {
	tests := []struct {
		name              string
		customSuggestions []string
		wantAutoGenerated bool // true = should have auto-generated suggestions, false = should have custom
	}{
		{
			name:              "backward compatibility - no custom suggestions",
			customSuggestions: nil,
			wantAutoGenerated: true,
		},
		{
			name:              "empty custom suggestions slice",
			customSuggestions: []string{},
			wantAutoGenerated: true,
		},
		{
			name:              "with custom suggestions",
			customSuggestions: []string{"Check the API documentation", "Verify the endpoint URL"},
			wantAutoGenerated: false,
		},
		{
			name:              "single custom suggestion",
			customSuggestions: []string{"Just one suggestion"},
			wantAutoGenerated: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := FormatValidationError("status_code", 200, 404, "GET /api/users", "", tt.customSuggestions...)
			errStr := err.Error()

			if tt.wantAutoGenerated {
				// Should contain auto-generated suggestions
				if !strings.Contains(errStr, "Verify the endpoint URL is correct") {
					t.Errorf("Expected auto-generated suggestion 'Verify the endpoint URL is correct', got:\n%s", errStr)
				}
			} else {
				// Should contain custom suggestions
				for _, suggestion := range tt.customSuggestions {
					if !strings.Contains(errStr, suggestion) {
						t.Errorf("Expected custom suggestion '%s', got:\n%s", suggestion, errStr)
					}
				}
			}
		})
	}
}

// TestFormatValidationErrorWithDetails_CustomSuggestions tests that custom suggestions work with detailed errors
func TestFormatValidationErrorWithDetails_CustomSuggestions(t *testing.T) {
	tests := []struct {
		name              string
		customSuggestions []string
		wantAutoGenerated bool
	}{
		{
			name:              "backward compatibility - no custom suggestions",
			customSuggestions: nil,
			wantAutoGenerated: true,
		},
		{
			name:              "with custom suggestions",
			customSuggestions: []string{"Check token format", "Verify OAuth scopes"},
			wantAutoGenerated: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := FormatValidationErrorWithDetails(
				"error_message",
				"invalid.*token",
				"access_denied",
				"OAuth validation",
				`{"error": "access_denied"}`,
				"error",
				"",  // location
				nil,  // relatedFields
				"regex pattern 'invalid.*token' did not match",
				"",
				[]string{"No matching error field found"},
				tt.customSuggestions...,
			)
			errStr := err.Error()

			// Should always have validation details
			if !strings.Contains(errStr, "No matching error field found") {
				t.Errorf("Expected validation detail 'No matching error field found', got:\n%s", errStr)
			}

			if tt.wantAutoGenerated {
				// Should contain auto-generated suggestions for error_message type
				if !strings.Contains(errStr, "Review request body for missing required fields") {
					t.Errorf("Expected auto-generated suggestion, got:\n%s", errStr)
				}
			} else {
				// Should contain custom suggestions
				for _, suggestion := range tt.customSuggestions {
					if !strings.Contains(errStr, suggestion) {
						t.Errorf("Expected custom suggestion '%s', got:\n%s", suggestion, errStr)
					}
				}
			}
		})
	}
}

// TestValidationError_AllFieldsOptional tests that all fields are truly optional
func TestValidationError_AllFieldsOptional(t *testing.T) {
	// Minimal usage with empty/zero values for all optional fields
	err := FormatValidationError("custom", "expected", "actual", "", "")
	errStr := err.Error()

	// Should have the basic error structure
	if !strings.Contains(errStr, "custom validation failed") {
		t.Errorf("Expected 'custom validation failed', got:\n%s", errStr)
	}

	if !strings.Contains(errStr, "Expected: expected") {
		t.Errorf("Expected 'Expected: expected', got:\n%s", errStr)
	}

	if !strings.Contains(errStr, "Actual:   actual") {
		t.Errorf("Expected 'Actual:   actual', got:\n%s", errStr)
	}

	// Should NOT have optional fields that weren't provided
	if strings.Contains(errStr, "Context:") {
		t.Errorf("Unexpected optional field 'Context:' in:\n%s", errStr)
	}
	if strings.Contains(errStr, "Field:") {
		t.Errorf("Unexpected optional field 'Field:' in:\n%s", errStr)
	}
	if strings.Contains(errStr, "Response:") {
		t.Errorf("Unexpected optional field 'Response:' in:\n%s", errStr)
	}
}

// TestValidationError_SuggestionsFieldOptional tests that suggestions field is optional
func TestValidationError_SuggestionsFieldOptional(t *testing.T) {
	// Create error with no suggestions
	ve := ValidationError{
		ErrorType: "test",
		Expected:       "expected",
		Actual:         "actual",
		// Suggestions field omitted (empty slice)
	}

	errStr := ve.Error()

	// Should have basic structure
	if !strings.Contains(errStr, "test validation failed") {
		t.Errorf("Expected 'test validation failed', got:\n%s", errStr)
	}

	// Should NOT have Suggestions section since it's empty
	if strings.Contains(errStr, "Suggestions:") {
		t.Errorf("Unexpected 'Suggestions:' in error output:\n%s", errStr)
	}
}
